<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Throwing exceptions to a generator</title>
		<link rel="stylesheet" href="../assert.css">
		<script src="../assert.js"></script>
	</head>
	<body>
		<script>
			function* NinjaGenerator() {
			  try{
			    yield "Hatori";
			    fail("The expected exception didn’t occur");
			  }
			  catch(e){
			    assert(e === "Catch this!", "Aha! We caught an exception");
			  }
			}
			 
			const ninjaIterator = NinjaGenerator();
			       
			const result1 = ninjaIterator.next();
			assert(result1.value === "Hatori", "We got Hatori");

			ninjaIterator.throw("Catch this!");
		</script>
	</body>
</html>
